version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        container_name: notifyer_web
        labels:
            - "traefik.http.routers.notifyer.rule=Host(`notifyer.localhost`)"
        volumes:
            - .:/application
            - ./tools/docker/logs/nginx:/var/log/nginx
            - ./tools/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            traefik:
                ipv4_address: 172.16.2.1

    php:
        build: ./tools/docker/php-fpm
        container_name: notifyer_php
        volumes:
            - .:/application
        networks:
            traefik:
                ipv4_address: 172.16.2.2

    db:
        image: mysql:8.0
        container_name: notifyer_db
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=notifyer
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        networks:
            traefik:
                ipv4_address: 172.16.2.3

networks:
    traefik:
        name: traefik
        external: true